/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;
import javax.swing.JInternalFrame;
import javax.swing.JPanel;
/**
 *
 * @author hp
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setTitle("Gestion Agence Immobilière");
        this.setExtendedState(MAXIMIZED_BOTH); // Plein écran
    }

    
    private void afficherFenetre(String titre, JPanel panel) {
        // 1. Nmss7o li kan mftou7 qbel (Optionnel)
        desktopPane.removeAll();
        desktopPane.repaint();

        // 2. Nsawbo fenetre dakhiliya
        JInternalFrame iframe = new JInternalFrame(titre, true, true, true, true);
        iframe.setSize(desktopPane.getWidth(), desktopPane.getHeight()); // Tchad l'ecran
        iframe.setContentPane(panel); // N7etto Form dyalk l'dakhel
        iframe.setVisible(true);

        // 3. Nzidoha f l'ecran l'k7el
        desktopPane.add(iframe);
        try {
            iframe.setMaximum(true); // Plein écran
        } catch (Exception e) {}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        PropMenu = new javax.swing.JMenuItem();
        BienMenu = new javax.swing.JMenuItem();
        LocationMenu = new javax.swing.JMenuItem();
        menuRecherche = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        menuDashboard = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion");

        PropMenu.setMnemonic('o');
        PropMenu.setText("Propriétaires");
        PropMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PropMenuActionPerformed(evt);
            }
        });
        fileMenu.add(PropMenu);

        BienMenu.setMnemonic('s');
        BienMenu.setText("Biens");
        BienMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BienMenuActionPerformed(evt);
            }
        });
        fileMenu.add(BienMenu);

        LocationMenu.setMnemonic('a');
        LocationMenu.setText("Locations");
        LocationMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationMenuActionPerformed(evt);
            }
        });
        fileMenu.add(LocationMenu);

        menuBar.add(fileMenu);

        menuRecherche.setMnemonic('e');
        menuRecherche.setText("Recherche");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Recherche Avancée");
        cutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cutMenuItemActionPerformed(evt);
            }
        });
        menuRecherche.add(cutMenuItem);

        menuBar.add(menuRecherche);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Statistiques");

        menuDashboard.setMnemonic('c');
        menuDashboard.setText("Tableau de Bord");
        menuDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDashboardActionPerformed(evt);
            }
        });
        helpMenu.add(menuDashboard);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LocationMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationMenuActionPerformed
        // TODO add your handling code here:
        afficherFenetre("Gestion des Locations", new presentation.LocationForm());
    }//GEN-LAST:event_LocationMenuActionPerformed

    private void PropMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PropMenuActionPerformed
        // TODO add your handling code here:
        afficherFenetre("Gestion des Propriétaires", new presentation.ProprietaireForm());
    }//GEN-LAST:event_PropMenuActionPerformed

    private void BienMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BienMenuActionPerformed
        // TODO add your handling code here:
        afficherFenetre("Gestion des Biens", new presentation.BienForm());
    }//GEN-LAST:event_BienMenuActionPerformed

    private void cutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cutMenuItemActionPerformed
        // TODO add your handling code here:
        desktopPane.removeAll();
        desktopPane.repaint();
        
        presentation.RechercheForm f = new presentation.RechercheForm();
        f.setSize(desktopPane.getWidth(), desktopPane.getHeight());
        f.setVisible(true);
        desktopPane.add(f);
        try { f.setMaximum(true); } catch(Exception e){}
    }//GEN-LAST:event_cutMenuItemActionPerformed

    private void menuDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDashboardActionPerformed
        // TODO add your handling code here:
        afficherFenetre("Tableau de Bord", new presentation.DashboardForm());
    }//GEN-LAST:event_menuDashboardActionPerformed

    /**
     * @param args the command line arguments
     */
  public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {}

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BienMenu;
    private javax.swing.JMenuItem LocationMenu;
    private javax.swing.JMenuItem PropMenu;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuDashboard;
    private javax.swing.JMenu menuRecherche;
    // End of variables declaration//GEN-END:variables

}
