/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import services.BienDao;
import services.ProprietaireDao;
import entities.Bien;
import entities.Proprietaire;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author hp
 */
public class RechercheForm extends javax.swing.JInternalFrame {
    private BienDao bienService = new BienDao();
    private ProprietaireDao propService = new ProprietaireDao();
    private DefaultTableModel model;
    /**
     * Creates new form RechercheForm
     */
    
     public RechercheForm() {
        initComponents();
        this.setClosable(true); // Bach tqdar tssedha
        this.setResizable(true); // Bach tkkberha
        this.setMaximizable(true);
        this.setTitle("Recherche Avancée");
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbType = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMotCle = new javax.swing.JTextField();
        btnChercher = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultat = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cbType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Biens", "Propriétaires" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Rechercher dans :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mot clé :");

        btnChercher.setBackground(new java.awt.Color(51, 255, 51));
        btnChercher.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnChercher.setForeground(new java.awt.Color(204, 0, 204));
        btnChercher.setText("Chercher ");
        btnChercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChercherActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnChercher, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(200, 200, 200)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbType, 0, 325, Short.MAX_VALUE)
                            .addComponent(txtMotCle))
                        .addGap(304, 304, 304))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbType, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMotCle, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btnChercher, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );

        tblResultat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblResultat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 81, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChercherActionPerformed
        // TODO add your handling code here:
     String choix = cbType.getSelectedItem().toString(); // Biens ou Propriétaires
        String motCle = txtMotCle.getText().toLowerCase(); // Dakchi li kteb
        
        model = new DefaultTableModel();
        
        if (choix.equals("Biens")) {
            // --- SCENARIO 1 : RECHERCHE BIENS ---
            // 1. Nqado rras d tableau
            model.addColumn("ID");
            model.addColumn("Type");
            model.addColumn("Ville");
            model.addColumn("Prix (DH)");
            model.addColumn("Propriétaire");
            
            // 2. N3mmro Data (Filtrage)
            for (Bien b : bienService.findAll()) {
                // Nqellbo f VILLE awla TYPE
                if (b.getVille().toLowerCase().contains(motCle) || b.getType().toLowerCase().contains(motCle)) {
                    String nomProp = (b.getProprietaire() != null) ? b.getProprietaire().getNom() : "Aucun";
                    model.addRow(new Object[]{
                        b.getId_bien(), b.getType(), b.getVille(), b.getPrixMensuel(), nomProp
                    });
                }
            }
            
        } else {
            // --- SCENARIO 2 : RECHERCHE PROPRIETAIRES ---
            // 1. Nqado rras d tableau
            model.addColumn("ID");
            model.addColumn("Nom");
            model.addColumn("Contact");
            model.addColumn("Adresse");
            
            // 2. N3mmro Data (Filtrage)
            for (Proprietaire p : propService.findAll()) {
                // Nqellbo f NOM awla CONTACT
                if (p.getNom().toLowerCase().contains(motCle) || p.getContact().toLowerCase().contains(motCle)) {
                    model.addRow(new Object[]{
                        p.getId_prop(), p.getNom(), p.getContact(), p.getAdresse()
                    });
                }
            }
        }
        
        // Afficher resultat f JTable
        tblResultat.setModel(model);
    }//GEN-LAST:event_btnChercherActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChercher;
    private javax.swing.JComboBox cbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResultat;
    private javax.swing.JTextField txtMotCle;
    // End of variables declaration//GEN-END:variables
}
